# Generated by Django 3.1.7 on 2021-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comparing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealerId', models.IntegerField()),
                ('CarId', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('IsNew', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=50)),
            ],
        ),
    ]
