# Generated by Django 3.1.7 on 2021-03-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobTestAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
